### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by FakeAlmir** [luckylukii/Random-Game#3]
Game is not finished like every project from luckylukii

**Comment by integr-dev** [comment]
truly isnt

**Comment by integr-dev** [comment]
[words.txt](https://github.com/user-attachments/files/15950658/words.txt)

**Comment by integr-dev** [comment]
@luckylukii 
read this

**Comment by integr-dev** [comment]
not finished

**Comment by FakeAlmir** [comment]
Still not finished lil bro
